function init(self)
	msg.post('.', 'acquire_input_focus')
	go.set("#sprite", "tint.w", 0)
	go.animate("#sprite", "tint.w", go.PLAYBACK_ONCE_FORWARD, 1, go.EASING_INEXPO, 1)
	go.animate('.', 'scale', go.PLAYBACK_LOOP_PINGPONG, 1.1, go.EASING_INOUTSINE, 2)
end

function on_input(self, action_id, action)
	if action_id == hash('start') and action.pressed then
		msg.post('main:/collections_manager', 'load_game')
	end
end